### ISSUE TITLE
Optionally load root namespace constants

### ISSUE THREAD

**Issue by chrisroberts** [chrisroberts/attribute_struct#5]
Provide option to make root namespace constants (i.e. ENV, File, Object, etc) available within the struct.

re: sparkleformation/sparkle_formation#63

**Comment by l8nite** [comment]
It'd be nice to see a way to inherit from Object instead of BasicObject for when we want to do ruby-ish things inside our blocks (like use `lambda`)

**Comment by ostap36** [comment]
+1 this will be extremely helpful.

**Comment by chrisroberts** [comment]
@l8nite what's the context you are using this in?

**Comment by ostap36** [comment]
@chrisroberts we are using this in a context of sparkleformation's dynamic, e.g. 
```
  dynamic!(:iam_policy, name, config) do
    properties.policy_document do
      statement array!(
        lambda do
          sid 'CFAllowedActionsAllResources'
          effect 'Allow'
          action array!(
            'cloudformation:DescribeStack*',
            'cloudformation:ListStack*'        
          )
          resource array!('*')
        end
...
```

**Comment by chrisroberts** [comment]
@ostap36 Hi! Thanks for the response. I'm doubtful that SparkleStruct's will enable kernel methods. Users will be able to enable them on demand, but introduces lots of places for name collisions (and I'd probably recommend against it, but that's up to the user's discretion). Is there any reason for not using the `->` operator?

**Comment by ostap36** [comment]
@chrisroberts thank you for the quick reply. Rubocop flags ```-> {...}``` as violations thus forcing an undesired ```# rubocop:disable Style/BlockDelimiters, Style/Lambda```

You've mentioned the ability to enable this on demand, how would one go about doing this?

**Comment by ostap36** [comment]
Hi @chrisroberts , do you have an example on how to enable kernel methods on demand? Ty

**Comment by chrisroberts** [comment]
@ostap36 Hi. Looking at this from the context of a sparkleformation template,  you can call `kernelify!` and the methods will be available after that point. For example:

```ruby 
SparkleFormation.new('test') do
  # At this point no Kernel methods are available so you must use `->`
  no_kernel array!(->{ a_key 'A value'})

  # Enable kernel methods
  kernelify!

  # Now things like `lambda` are available
  with_kernel array!(lambda{ a_key 'A value'})
end
```

and you'll end up with:

```json
{
  "NoKernel": [
    {
      "AKey": "A value"
    }
  ],
  "WithKernel": [
    {
      "AKey": "A value"
    }
  ]
}
```

Hope that helps. And since this issue didn't get closed when the support was merged in, I'm going to close this up now.

**Comment by ostap36** [comment]
Got it thx.
